apiVersion: v1  
kind: Service                           # Type of the kubernetes resource
metadata:
  name: forum-backend-app             # Name of the Kubernetes resource
  labels:                               # Labels that will be applied to the resource
    app: forum-backend-app
spec:
  type: NodePort                        # Gives each node an external IP that’s accessible from outside the cluster and also opens a Port.
  selector:
    app: forum-backend-app            # Selects any Pod with labels `app=forum-backend-app`
  ports: 
  - name: http
    port: 8080
    targetPort: 8080