FROM golang:1.15-alpine

# Install Git
# Git is required for fetching dependencies
RUN apk update && apk add --no-cache git

# Set the current working directory inside the container
WORKDIR /usr/src/app

# Copy go mod and sum file
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and the go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the working Directory inside the container
COPY . .

# Run test
CMD CGO_ENABLED=0 GOOS=linux go test -v ./tests/...