version: "3"
services:
  app_test:
    container_name: forum_app_test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api_test:/usr/src/app/
    depends_on:
      # - postgres_test
      - mysql_test
    networks:
      - forum_stack_test

  # postgres_test:
  #   image: postgres:latest
  #   container_name: forum_db_test_postgres
  #   environment:
  #     - POSTGRES_USER=${TEST_DB_USER}
  #     - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
  #     - POSTGRES_DB=${TEST_DB_NAME}
  #     - DATABASE_HOST=${TEST_DB_HOST}
  #   ports:
  #     - 5555:5432
  #   volumes:
  #     - database_postgres_test:/var/lib/postgresql/data
  #   networks:
  #     - forum_stack_test
  
  mysql_test:
    image: mysql:5.7
    container_name: forum_db_test_mysql    
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=${TEST_DB_HOST}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=${TEST_DB_PASSWORD}
      - MYSQL_USER=${TEST_DB_USER}
      - MYSQL_PASSWORD=${TEST_DB_PASSWORD}
      - MYSQL_DATABASE=${TEST_DB_NAME}
    volumes:
      - database_mysql_test:/var/lib/mysql
    restart: on-failure
    networks:
      - forum_stack_test

volumes:
  api_test:
  # database_postgres_test:
  database_mysql_test:

networks:
  forum_stack_test:
    driver: bridge