version: "3"
services:
  app:
    container_name: forum_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - forum-backend-mysql
      # - forum-backend-postgres    # Uncomment this when using postgres.
    networks:
      - forum_network

  # forum-backend-postgres:
  #   image: postgres:latest
  #   container_name: forum_db_postgres
  #   environment:
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #     - DATABASE_HOST=${DB_HOST}
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - database_postgres:/var/lib/postgresql/data
  #   networks:
  #     - forum_network

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_container
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   depends_on:
  #     - forum-backend-postgres
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - forum_network
  #   restart: unless-stopped

  forum-backend-mysql:
    image: mysql:5.7
    container_name: forum_db_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - forum_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - forum-backend-mysql
    environment:
      - PMA_HOST=forum-backend-mysql  # Note the mysql. Must be the name of the what you used as the mysql service.
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 9090:80
    restart: always
    networks:
      - forum_network

volumes:
  api:
  database_mysql:
  # database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  forum_network:
    driver: bridge
