apiVersion: v1                           # API version
kind: Service                            # Type of kubernetes resource 
metadata:
  name: forum-backend-mysql              # Name of the resource
  labels:                                # Labels that will be applied to the resource
    app: forum-backend-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
  selector:                              # Selects any Pod with labels `app=forum-backend-mysql,tier=mysql`
    app: forum-backend-mysql
    tier: mysql 